version: '3'
services:
  wenancech:
    container_name: wenancech
    environment:
        spring.data.mongodb.uri: "mongodb://mongoDB:27017/wenancechDB"
        buenbit.service.url: "https://be.buenbit.com/api"
        logging.level.org.springframework.data: "debug"
        server.port: 8080
        TZ: "GMT-3"
    image: wenancech:latest
    ports:
        - "8080:8080"
    links:
      - mongoDB
    networks:
        - spring-cloud-network

  mongoDB:
    image: mongo:latest
    ports:
        - "27017:27017"
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge
